/* eslint-disable */
const LANDSCAPE = {
  categories: [
    {
      id: 'inference',
      name: 'Inference Benchmarking',
      description:
        'Tools for measuring LLM and model inference performance — throughput, latency, concurrency, and scalability across hardware.',
      color: '#2563EB',
      colorDark: '#3B82F6',
    },
    {
      id: 'benchmark-orchestration',
      name: 'Benchmark Orchestration',
      description:
        'Frameworks that automate and orchestrate benchmark runs across environments — matrix testing, distributed execution, reproducible methodology, and results pipelines.',
      color: '#B45309',
      colorDark: '#F59E0B',
    },
    {
      id: 'quality',
      name: 'LLM Quality & Accuracy',
      description:
        'Frameworks for holistic evaluation of language model capabilities across reasoning, knowledge, calibration, fairness, and general task accuracy.',
      color: '#D97706',
      colorDark: '#FBBF24',
    },
    {
      id: 'code',
      name: 'Code Generation',
      description:
        'Benchmarks measuring LLM ability to write, complete, repair, and autonomously debug code across languages, complexity levels, and real-world software engineering tasks.',
      color: '#0891B2',
      colorDark: '#22D3EE',
    },
    {
      id: 'agent',
      name: 'Agent & Tool Use',
      description:
        'Evaluations for LLM-powered agents operating in tool-use, function-calling, web-browsing, and multi-step environment scenarios.',
      color: '#BE185D',
      colorDark: '#F472B6',
    },
    {
      id: 'rag',
      name: 'RAG & Retrieval Evaluation',
      description:
        'Frameworks for evaluating Retrieval-Augmented Generation pipelines — faithfulness, answer relevancy, context quality, and end-to-end retrieval accuracy.',
      color: '#0D9488',
      colorDark: '#2DD4BF',
    },
    {
      id: 'embedding',
      name: 'Embedding Quality',
      description:
        'Benchmarks that evaluate embedding model quality across retrieval, classification, clustering, and semantic similarity tasks.',
      color: '#7C3AED',
      colorDark: '#A78BFA',
    },
    {
      id: 'audio',
      name: 'Audio & Speech',
      description:
        'Tools for benchmarking speech-to-text, audio transcription accuracy, and real-time audio model throughput.',
      color: '#059669',
      colorDark: '#34D399',
    },
    {
      id: 'safety',
      name: 'Safety & Alignment',
      description:
        'Benchmarks that evaluate LLM truthfulness, refusal behavior, resistance to jailbreaks, and alignment with human values and safety guidelines.',
      color: '#A21CAF',
      colorDark: '#E879F9',
    },
    {
      id: 'multimodal',
      name: 'Multimodal',
      description:
        'Benchmarks for vision-language and multimodal models — spanning image understanding, visual reasoning, video comprehension, and cross-modal question answering.',
      color: '#4338CA',
      colorDark: '#818CF8',
    },
    {
      id: 'security',
      name: 'Security & Vulnerability',
      description:
        'Benchmarks focused on security evaluation, vulnerability localization, and red-teaming of AI systems.',
      color: '#DC2626',
      colorDark: '#F87171',
    },
  ],

  tools: [
    // ── Inference ──────────────────────────────────────────────────────────
    {
      id: 'vllm-serve',
      name: 'vLLM Benchmark Serve',
      shortName: 'vLLM Serve',
      initials: 'vS',
      logo: 'logos/vllm-serve.png',
      stars: 88879,
      forks: 20593,
      description:
        'Online serving benchmark that measures TTFT, TPOT, inter-token latency, and request/token throughput under concurrent load against a running vLLM server.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online'],
      url: 'https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py',
      license: 'Apache 2.0',
      org: 'vLLM Project',
      metrics: [
        'TTFT – Time To First Token',
        'TPOT – Time Per Output Token',
        'ITL – Inter-token Latency',
        'Request throughput (req/s)',
        'Output token throughput (tok/s)',
      ],
      tags: ['vllm', 'online', 'serving', 'latency'],
    },
    {
      id: 'vllm-throughput',
      name: 'vLLM Benchmark Throughput',
      shortName: 'vLLM Throughput',
      initials: 'vT',
      logo: 'logos/vllm-throughput.png',
      stars: 88879,
      forks: 20593,
      description:
        'Offline static throughput benchmark measuring maximum tokens-per-second in batch processing mode, without request-level latency constraints.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['offline'],
      url: 'https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py',
      license: 'Apache 2.0',
      org: 'vLLM Project',
      metrics: [
        'Total throughput (tok/s)',
        'Prompt throughput (tok/s)',
        'Generation throughput (tok/s)',
      ],
      tags: ['vllm', 'offline', 'batch', 'throughput'],
    },
    {
      id: 'mlperf',
      name: 'MLPerf Inference',
      shortName: 'MLPerf',
      initials: 'ML',
      logo: 'logos/mlperf.png',
      stars: 1616,
      forks: 646,
      description:
        'Industry-standard ML inference benchmark suite from MLCommons covering image classification, object detection, NLP, LLM, and recommendation tasks with offline and server (online) scenarios.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online', 'offline'],
      url: 'https://mlcommons.org/benchmarks/inference/',
      license: 'Apache 2.0',
      org: 'MLCommons',
      metrics: [
        'Samples / second',
        '90th-percentile latency',
        'Queries per second (QPS)',
      ],
      tags: ['mlcommons', 'industry-standard', 'llm', 'vision'],
    },
    {
      id: 'guidellm',
      name: 'GuideLLM',
      shortName: 'GuideLLM',
      initials: 'GL',
      logo: 'logos/guidellm.png',
      stars: 1495,
      forks: 209,
      description:
        'LLM serving evaluation framework from Neural Magic / Red Hat that sweeps concurrency rates and measures performance under sustained load across text, image, audio, and video modalities — producing detailed latency-throughput profiles via synchronous, concurrent, throughput, constant, Poisson, and sweep load profiles.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online', 'audio'],
      url: 'https://github.com/neuralmagic/guidellm',
      license: 'Apache 2.0',
      org: 'Neural Magic / Red Hat',
      metrics: [
        'Request throughput (req/s)',
        'TTFT',
        'ITL',
        'Token throughput (tok/s)',
      ],
      tags: ['guidellm', 'serving', 'concurrency', 'red-hat', 'multimodal', 'audio'],
    },
    {
      id: 'inferx',
      name: 'Inference X',
      shortName: 'Inference X',
      initials: 'IX',
      logo: 'logos/inferx.png',
      stars: 1377,
      forks: 254,
      description:
        'SemiAnalysis\'s LLM inference benchmarking platform — tracks and compares throughput, latency, and cost efficiency across GPU hardware, serving frameworks, and quantization strategies for leading open-source models.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online', 'offline'],
      url: 'https://github.com/SemiAnalysisAI/InferenceX',
      license: '',
      org: 'SemiAnalysis',
      metrics: [
        'Throughput (tok/s)',
        'Latency (p50 / p95 / p99)',
        'Cost per million tokens',
        'Hardware efficiency',
      ],
      tags: ['inferx', 'semianalysis', 'benchmarking', 'cost'],
    },
    {
      id: 'genai-perf',
      name: 'GenAI-Perf',
      shortName: 'GenAI-Perf',
      initials: 'GP',
      logo: 'logos/genai-perf.png',
      stars: 153,
      forks: 49,
      description:
        "NVIDIA's benchmarking CLI for generative AI inference servers — measures TTFT, ITL, and token throughput for LLM and multimodal models served via Triton or any OpenAI-compatible endpoint.",
      category: 'inference',
      hardware: ['gpu'],
      types: ['online'],
      url: 'https://github.com/triton-inference-server/perf_analyzer/tree/main/genai-perf',
      license: 'Apache 2.0',
      org: 'NVIDIA',
      metrics: [
        'TTFT – Time To First Token',
        'ITL – Inter-token Latency',
        'Output token throughput (tok/s)',
        'Request throughput (req/s)',
      ],
      tags: ['nvidia', 'triton', 'genai', 'serving'],
    },
    {
      id: 'llmperf',
      name: 'LLMPerf',
      shortName: 'LLMPerf',
      initials: 'LP',
      logo: 'logos/llmperf.png',
      stars: 1129,
      forks: 203,
      description:
        "Anyscale's open-source framework for evaluating LLM API performance — sweeps concurrency levels, measures TTFT and inter-token latency, and produces comparative reports across providers and models. Archived read-only in December 2025; use GuideLLM or AIPerf for ongoing API load testing.",
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online'],
      url: 'https://github.com/ray-project/llmperf',
      status: 'archived',
      lastReviewed: '2026-08-12',
      license: 'Apache 2.0',
      org: 'Anyscale / Ray',
      metrics: [
        'TTFT – Time To First Token',
        'Inter-token latency',
        'Output token throughput (tok/s)',
        'Error rate',
      ],
      tags: ['anyscale', 'ray', 'api', 'concurrency', 'archived'],
    },
    {
      id: 'perf-analyzer',
      name: 'Perf Analyzer',
      shortName: 'Perf Analyzer',
      initials: 'PA',
      logo: 'logos/perf-analyzer.png',
      stars: 153,
      forks: 49,
      description:
        "NVIDIA Triton Inference Server's built-in load-testing and profiling tool — sends concurrent requests, profiles GPU utilization, and reports latency percentiles and throughput across model backends.",
      category: 'inference',
      hardware: ['gpu'],
      types: ['online', 'offline'],
      url: 'https://github.com/triton-inference-server/perf_analyzer',
      license: 'BSD 3-Clause',
      org: 'NVIDIA',
      metrics: [
        'Throughput (infer/s)',
        'Latency (p50 / p90 / p99)',
        'GPU utilization',
        'Memory usage',
      ],
      tags: ['nvidia', 'triton', 'profiling', 'gpu'],
    },
    {
      id: 'inference-perf',
      name: 'inference-perf',
      shortName: 'inference-perf',
      initials: 'IP',
      logo: 'logos/inference-perf.png',
      stars: 220,
      forks: 113,
      description:
        'Kubernetes SIG inference benchmarking tool that drives concurrent, constant-rate, and Poisson load profiles against OpenAI-compatible endpoints, producing JSON and PNG reports for text workloads.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online'],
      url: 'https://github.com/kubernetes-sigs/inference-perf',
      license: 'Apache 2.0',
      org: 'Kubernetes SIGs',
      metrics: [
        'Request throughput (req/s)',
        'TTFT – Time To First Token',
        'ITL – Inter-token Latency',
        'Token throughput (tok/s)',
      ],
      tags: ['kubernetes', 'k8s', 'inference', 'serving', 'concurrency'],
    },
    {
      id: 'genai-bench',
      name: 'GenAI-Bench',
      shortName: 'GenAI-Bench',
      initials: 'GB',
      logo: 'logos/genai-bench.png',
      stars: 318,
      forks: 56,
      description:
        'SGLang project benchmarking CLI for generative AI inference — supports text, image, embedding, and re-ranking modalities against OpenAI-compatible and hosted cloud backends, with concurrent load profiles and XLSX/PNG output.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online'],
      url: 'https://github.com/sgl-project/genai-bench',
      license: 'Apache 2.0',
      org: 'SGLang Project',
      metrics: [
        'Request throughput (req/s)',
        'TTFT – Time To First Token',
        'ITL – Inter-token Latency',
        'Token throughput (tok/s)',
      ],
      tags: ['sglang', 'genai', 'multimodal', 'embedding', 'rerank'],
    },
    {
      id: 'ollama-benchmark',
      name: 'Ollama Benchmark',
      shortName: 'Ollama Bench',
      initials: 'OB',
      logo: 'logos/ollama-benchmark.png',
      stars: 383,
      forks: 45,
      description:
        'Lightweight benchmarking tool for Ollama — runs synchronous single-request load tests against the Ollama /completions endpoint to measure local model throughput and latency.',
      category: 'inference',
      hardware: ['cpu', 'gpu'],
      types: ['online'],
      url: 'https://github.com/aidatatools/ollama-benchmark',
      license: 'MIT',
      org: 'AI Data Tools',
      metrics: [
        'Tokens per second',
        'Latency per request',
      ],
      tags: ['ollama', 'local', 'benchmark', 'synchronous'],
    },

    // ── LLM Quality & Accuracy ─────────────────────────────────────────────
    {
      id: 'helm',
      name: 'HELM',
      shortName: 'HELM',
      initials: 'HE',
      logo: 'logos/helm.png',
      stars: 2875,
      forks: 406,
      description:
        "Holistic Evaluation of Language Models — Stanford's comprehensive framework that evaluates LLMs across 42 scenarios and 7 metrics (accuracy, calibration, robustness, fairness, efficiency) to produce a multi-dimensional model profile.",
      category: 'quality',
      hardware: ['cpu', 'gpu'],
      types: ['quality'],
      url: 'https://crfm.stanford.edu/helm/',
      license: 'Apache 2.0',
      org: 'Stanford CRFM',
      metrics: [
        'Accuracy',
        'Calibration (ECE)',
        'Robustness',
        'Fairness',
        'Efficiency (tokens/s)',
      ],
      tags: ['helm', 'stanford', 'holistic', 'evaluation'],
    },
    {
      id: 'lm-eval',
      name: 'LM Evaluation Harness',
      shortName: 'LM Eval',
      initials: 'LE',
      logo: 'logos/lm-eval.png',
      stars: 13604,
      forks: 3477,
      description:
        "EleutherAI's unified framework for evaluating autoregressive LLMs across 200+ tasks — widely used for public leaderboards and reproducible benchmarks, supporting MMLU, HellaSwag, ARC, TruthfulQA, and many more.",
      category: 'quality',
      hardware: ['cpu', 'gpu'],
      types: ['quality'],
      url: 'https://github.com/EleutherAI/lm-evaluation-harness',
      license: 'MIT',
      org: 'EleutherAI',
      metrics: [
        'Accuracy (task-specific)',
        'Normalized accuracy',
        'F1 score',
        'BLEU / ROUGE (generation tasks)',
      ],
      tags: ['eleutherai', 'evaluation', 'mmlu', 'openllm', 'harness'],
    },
    {
      id: 'openai-evals',
      name: 'OpenAI Evals',
      shortName: 'OAI Evals',
      initials: 'OE',
      logo: 'logos/openai-evals.png',
      stars: 19152,
      forks: 3052,
      description:
        "OpenAI's framework for evaluating LLMs and LLM-powered systems — supports custom eval creation with model-graded, classification, and fuzzy-match eval types, and includes a large library of community-contributed evals. Community maintenance is limited; OpenAI's hosted Evals platform becomes read-only in October 2026 and shuts down in November 2026.",
      category: 'quality',
      hardware: ['cpu', 'gpu'],
      types: ['quality'],
      url: 'https://github.com/openai/evals',
      license: 'MIT',
      org: 'OpenAI',
      metrics: [
        'Accuracy',
        'Model-graded score',
        'Pass rate',
        'Custom eval metrics',
      ],
      tags: ['openai', 'evals', 'custom-eval', 'model-graded'],
    },

    // ── Code Generation ────────────────────────────────────────────────────
    {
      id: 'humaneval',
      name: 'HumanEval',
      shortName: 'HumanEval',
      initials: 'HV',
      logo: 'logos/humaneval.png',
      stars: 3333,
      forks: 456,
      description:
        "OpenAI's hand-written Python coding benchmark — 164 programming problems with unit tests, measuring functional correctness of generated code via pass@k. The de facto standard for LLM code generation evaluation.",
      category: 'code',
      hardware: ['cpu', 'gpu'],
      types: ['code'],
      url: 'https://github.com/openai/human-eval',
      license: 'MIT',
      org: 'OpenAI',
      metrics: [
        'pass@1',
        'pass@10',
        'pass@100',
      ],
      tags: ['humaneval', 'openai', 'code-generation', 'python'],
    },
    {
      id: 'swe-bench',
      name: 'SWE-bench',
      shortName: 'SWE-bench',
      initials: 'SW',
      logo: 'logos/swe-bench.png',
      stars: 5624,
      forks: 937,
      description:
        'Software Engineering Benchmark — 2,294 real GitHub issues from popular Python repositories, testing whether LLM-generated patches can resolve actual bugs. The leading benchmark for evaluating autonomous coding agents.',
      category: 'code',
      hardware: ['cpu', 'gpu'],
      types: ['code', 'agent'],
      url: 'https://www.swebench.com',
      license: 'MIT',
      org: 'Princeton NLP',
      metrics: [
        '% Resolved (patch passes all tests)',
        'Resolve rate on SWE-bench Verified',
        'Resolve rate on SWE-bench Lite',
      ],
      tags: ['swe-bench', 'princeton', 'github', 'patch', 'agent'],
    },
    {
      id: 'bigcodebench',
      name: 'BigCodeBench',
      shortName: 'BigCodeBench',
      initials: 'BC',
      logo: 'logos/bigcodebench.png',
      stars: 519,
      forks: 75,
      description:
        'A challenging coding benchmark with 1,140 tasks requiring complex Python function completion using diverse libraries. Tests real-world software engineering skills beyond algorithmic problems, covering data science, ML, and system APIs. Repository archived in July 2026; leaderboard results remain available for historical comparison.',
      category: 'code',
      hardware: ['cpu', 'gpu'],
      types: ['code'],
      url: 'https://github.com/bigcode-project/bigcodebench',
      status: 'archived',
      lastReviewed: '2026-08-12',
      license: 'Apache 2.0',
      org: 'BigCode Project',
      metrics: [
        'pass@1 (Complete)',
        'pass@1 (Instruct)',
        'Calibrated pass@1',
      ],
      tags: ['bigcodebench', 'bigcode', 'function-completion', 'libraries', 'archived'],
    },
    {
      id: 'livecodebench',
      name: 'LiveCodeBench',
      shortName: 'LiveCodeBench',
      initials: 'LC',
      logo: 'logos/livecodebench.png',
      stars: 928,
      forks: 197,
      description:
        'Holistic and contamination-free coding benchmark that continuously collects fresh problems from LeetCode, AtCoder, and CodeForces — updated monthly to prevent training-data leakage, covering code generation, testing, and repair.',
      category: 'code',
      hardware: ['cpu', 'gpu'],
      types: ['code'],
      url: 'https://livecodebench.github.io',
      license: 'MIT',
      org: 'LiveCodeBench',
      metrics: [
        'pass@1',
        'Easy / Medium / Hard breakdown',
        'Code execution accuracy',
      ],
      tags: ['livecodebench', 'contamination-free', 'leetcode', 'competitive'],
    },

    // ── Agent & Tool Use ───────────────────────────────────────────────────
    {
      id: 'bfcl',
      name: 'Berkeley BFCL',
      shortName: 'BFCL',
      initials: 'BF',
      logo: 'logos/bfcl.png',
      stars: 12992,
      forks: 1398,
      description:
        'Berkeley Function-Calling Leaderboard — evaluates LLM tool-use accuracy across 2,000+ function-calling tasks in Python, Java, SQL, REST API, and parallel/nested scenarios. The de facto leaderboard for structured tool invocation.',
      category: 'agent',
      hardware: ['cpu', 'gpu'],
      types: ['agent'],
      url: 'https://gorilla.cs.berkeley.edu/leaderboard.html',
      license: 'Apache 2.0',
      org: 'UC Berkeley',
      metrics: [
        'Overall accuracy',
        'AST evaluation score',
        'Executable function accuracy',
        'Irrelevance detection accuracy',
      ],
      tags: ['bfcl', 'berkeley', 'function-calling', 'tool-use'],
    },
    {
      id: 'agentbench',
      name: 'AgentBench',
      shortName: 'AgentBench',
      initials: 'AB',
      logo: 'logos/agentbench.png',
      stars: 3661,
      forks: 273,
      description:
        "THUDM's multi-environment benchmark for evaluating LLMs as autonomous agents across 8 distinct environments — including OS shell, database, web browser, code execution, and digital card games.",
      category: 'agent',
      hardware: ['cpu', 'gpu'],
      types: ['agent'],
      url: 'https://github.com/THUDM/AgentBench',
      license: 'Apache 2.0',
      org: 'Tsinghua (THUDM)',
      metrics: [
        'Overall score',
        'Per-environment task success rate',
        'Average steps to completion',
      ],
      tags: ['agentbench', 'thudm', 'tsinghua', 'multi-environment'],
    },
    {
      id: 'tau-bench',
      name: 'τ-bench',
      shortName: 'τ-bench',
      initials: 'τB',
      logo: 'logos/tau-bench.png',
      stars: 1375,
      forks: 213,
      description:
        'Tool-agent evaluation benchmark from Sierra Research — simulates realistic customer service tasks where agents must call tools, follow policies, and handle multi-turn user interactions to measure real-world agentic reliability.',
      category: 'agent',
      hardware: ['cpu', 'gpu'],
      types: ['agent'],
      url: 'https://github.com/sierra-research/tau-bench',
      license: 'MIT',
      org: 'Sierra Research',
      metrics: [
        'Task success rate',
        'Policy compliance rate',
        'Tool call accuracy',
        'Average turns to resolution',
      ],
      tags: ['tau-bench', 'sierra', 'tool-use', 'customer-service'],
    },
    {
      id: 'webarena',
      name: 'WebArena',
      shortName: 'WebArena',
      initials: 'WA',
      logo: 'logos/webarena.png',
      stars: 1577,
      forks: 243,
      description:
        'Realistic web-based environment for evaluating autonomous agents — 812 long-horizon tasks across e-commerce, social forums, code repositories, and CMS platforms running in fully functional locally-hosted websites.',
      category: 'agent',
      hardware: ['cpu', 'gpu'],
      types: ['agent'],
      url: 'https://webarena.dev',
      license: 'Apache 2.0',
      org: 'CMU / Ohio State University',
      metrics: [
        'Task success rate',
        'Intent satisfaction rate',
        'Steps per task',
      ],
      tags: ['webarena', 'cmu', 'web-agent', 'browser', 'long-horizon'],
    },

    // ── RAG & Retrieval Evaluation ─────────────────────────────────────────
    {
      id: 'ragas',
      name: 'RAGAS',
      shortName: 'RAGAS',
      initials: 'RG',
      logo: 'logos/ragas.png',
      stars: 15291,
      forks: 1623,
      description:
        'Reference-free evaluation framework for Retrieval-Augmented Generation pipelines — scores faithfulness, answer relevancy, context precision, and context recall without requiring human-annotated ground-truth labels.',
      category: 'rag',
      hardware: ['cpu', 'gpu'],
      types: ['rag'],
      url: 'https://github.com/explodinggradients/ragas',
      license: 'Apache 2.0',
      org: 'Exploding Gradients',
      metrics: [
        'Faithfulness',
        'Answer relevancy',
        'Context precision',
        'Context recall',
        'RAGAS score',
      ],
      tags: ['ragas', 'retrieval', 'rag', 'faithfulness'],
    },
    {
      id: 'deepeval',
      name: 'DeepEval',
      shortName: 'DeepEval',
      initials: 'DV',
      logo: 'logos/deepeval.png',
      stars: 17553,
      forks: 1791,
      description:
        'Open-source LLM evaluation framework with 14+ metrics for RAG pipelines, LLM outputs, and agentic systems — including G-Eval, hallucination detection, answer relevancy, and custom LLM-as-judge evaluators.',
      category: 'rag',
      hardware: ['cpu', 'gpu'],
      types: ['rag', 'quality'],
      url: 'https://github.com/confident-ai/deepeval',
      license: 'Apache 2.0',
      org: 'Confident AI',
      metrics: [
        'Hallucination score',
        'Answer relevancy',
        'G-Eval (custom criteria)',
        'Bias & toxicity score',
      ],
      tags: ['deepeval', 'confident-ai', 'rag', 'hallucination'],
    },
    {
      id: 'trulens',
      name: 'TruLens',
      shortName: 'TruLens',
      initials: 'TL',
      logo: 'logos/trulens.png',
      stars: 3506,
      forks: 319,
      description:
        'LLM application evaluation and observability framework from TruEra — instruments RAG pipelines to measure answer relevance, groundedness, and context relevance, with a dashboard for iterative improvement.',
      category: 'rag',
      hardware: ['cpu', 'gpu'],
      types: ['rag'],
      url: 'https://github.com/truera/trulens',
      license: 'MIT',
      org: 'TruEra',
      metrics: [
        'Answer relevance',
        'Groundedness',
        'Context relevance',
        'Feedback function scores',
      ],
      tags: ['trulens', 'truera', 'rag', 'observability'],
    },
    {
      id: 'promptfoo',
      name: 'Promptfoo',
      shortName: 'Promptfoo',
      initials: 'PF',
      logo: 'logos/promptfoo.png',
      stars: 24167,
      forks: 2177,
      description:
        'Open-source LLM testing and red-teaming tool — runs prompt test suites with assertions, A/B tests prompts across providers, and includes automated red-teaming for safety vulnerabilities in LLM applications.',
      category: 'rag',
      hardware: ['cpu', 'gpu'],
      types: ['rag', 'security'],
      url: 'https://github.com/promptfoo/promptfoo',
      license: 'MIT',
      org: 'Promptfoo',
      metrics: [
        'Pass / fail rate per assertion',
        'Red-team vulnerability rate',
        'Prompt regression score',
        'Provider comparison score',
      ],
      tags: ['promptfoo', 'testing', 'red-team', 'prompt'],
    },

    // ── Embedding ──────────────────────────────────────────────────────────
    {
      id: 'mteb',
      name: 'MTEB',
      shortName: 'MTEB',
      initials: 'MT',
      logo: 'logos/mteb.png',
      stars: 3390,
      forks: 664,
      description:
        'Massive Text Embedding Benchmark — evaluates embedding models across 8 task types (retrieval, classification, clustering, STS, summarization, …) and 100+ datasets in 112 languages.',
      category: 'embedding',
      hardware: ['cpu', 'gpu'],
      types: ['embedding'],
      url: 'https://github.com/embeddings-benchmark/mteb',
      license: 'Apache 2.0',
      org: 'Hugging Face / MTEB',
      metrics: [
        'NDCG@10 (retrieval)',
        'MAP',
        'Accuracy (classification)',
        'Spearman correlation (STS)',
      ],
      tags: ['mteb', 'embedding', 'retrieval', 'huggingface'],
    },
    {
      id: 'beir',
      name: 'BEIR',
      shortName: 'BEIR',
      initials: 'BE',
      logo: 'logos/beir.png',
      stars: 2269,
      forks: 250,
      description:
        'Benchmarking Information Retrieval — a heterogeneous benchmark with 18+ datasets spanning biomedical, financial, scientific, and web retrieval. Tests zero-shot transferability of dense and sparse retrieval models.',
      category: 'embedding',
      hardware: ['cpu', 'gpu'],
      types: ['embedding'],
      url: 'https://github.com/beir-cellar/beir',
      license: 'Apache 2.0',
      org: 'BEIR Cellar',
      metrics: [
        'NDCG@10',
        'Recall@100',
        'MAP@100',
      ],
      tags: ['beir', 'retrieval', 'zero-shot', 'information-retrieval'],
    },
    {
      id: 'air-bench-retrieval',
      name: 'AIR-Bench',
      shortName: 'AIR-Bench',
      initials: 'AI',
      logo: 'logos/air-bench-retrieval.png',
      stars: 167,
      forks: 10,
      description:
        'Automated Information Retrieval Benchmark — evaluates embedding models on long-form retrieval tasks designed for RAG workloads, covering finance, legal, medical, and general web corpora.',
      category: 'embedding',
      hardware: ['cpu', 'gpu'],
      types: ['embedding'],
      url: 'https://github.com/AIR-Bench/AIR-Bench',
      license: 'Apache 2.0',
      org: 'AIR-Bench',
      metrics: [
        'NDCG@10',
        'MRR@10',
        'Recall@10',
      ],
      tags: ['air-bench', 'retrieval', 'rag', 'embedding'],
    },

    // ── Audio ──────────────────────────────────────────────────────────────
    {
      id: 'whisper-bench',
      name: 'Whisper Benchmarking',
      shortName: 'Whisper',
      initials: 'WH',
      logo: 'logos/whisper-bench.png',
      stars: 107144,
      forks: 13002,
      description:
        'Evaluation of OpenAI Whisper and Faster-Whisper models for speech-to-text accuracy (WER/CER) and real-time transcription throughput on diverse audio datasets.',
      category: 'audio',
      hardware: ['cpu', 'gpu'],
      types: ['audio'],
      url: 'https://github.com/openai/whisper',
      license: 'MIT',
      org: 'OpenAI',
      metrics: [
        'WER – Word Error Rate',
        'CER – Character Error Rate',
        'Real-time factor (RTF)',
        'Tokens / second',
      ],
      tags: ['whisper', 'asr', 'transcription', 'openai'],
    },
    {
      id: 'esb',
      name: 'Open ASR Leaderboard (ESB)',
      shortName: 'Open ASR',
      initials: 'ES',
      logo: 'logos/esb.png',
      stars: 236,
      forks: 117,
      description:
        'End-to-end Speech Benchmark — evaluates ASR models across 8 English datasets covering clean speech, accented speech, telephone conversations, and noisy environments, producing a composite WER score for fair multi-domain comparison.',
      category: 'audio',
      hardware: ['cpu', 'gpu'],
      types: ['audio'],
      url: 'https://huggingface.co/spaces/hf-audio/open_asr_leaderboard',
      license: 'Apache 2.0',
      org: 'Hugging Face',
      metrics: [
        'WER – Word Error Rate (composite)',
        'Per-dataset WER breakdown',
        'RTF – Real-time Factor',
      ],
      tags: ['esb', 'asr', 'speech', 'multi-domain', 'huggingface'],
    },
    {
      id: 'voice-bench',
      name: 'VoiceBench',
      shortName: 'VoiceBench',
      initials: 'VB',
      logo: 'logos/voice-bench.png',
      stars: 382,
      forks: 29,
      description:
        'End-to-end voice assistant benchmark evaluating the full pipeline — ASR, language understanding, and response generation — across accents, noise conditions, and instruction-following tasks.',
      category: 'audio',
      hardware: ['cpu', 'gpu'],
      types: ['audio'],
      url: 'https://github.com/MatthewCYM/VoiceBench',
      license: 'Apache 2.0',
      org: 'VoiceBench',
      metrics: [
        'Task accuracy',
        'WER – Word Error Rate',
        'Instruction-following score',
      ],
      tags: ['voicebench', 'voice-assistant', 'asr', 'end-to-end'],
    },
    {
      id: 'superb',
      name: 'SUPERB',
      shortName: 'SUPERB',
      initials: 'SU',
      logo: 'logos/superb.png',
      stars: 2560,
      forks: 534,
      description:
        'Speech processing Universal PERformance Benchmark — evaluates speech foundation models across 10 tasks including ASR, speaker identification, emotion recognition, keyword spotting, and spoken language understanding.',
      category: 'audio',
      hardware: ['cpu', 'gpu'],
      types: ['audio'],
      url: 'https://superbbenchmark.org',
      license: 'MIT',
      org: 'National Taiwan University',
      metrics: [
        'WER (ASR)',
        'Accuracy (classification tasks)',
        'F1 score (SER, SID)',
        'Diarization error rate',
      ],
      tags: ['superb', 'speech', 'foundation-models', 'multi-task'],
    },

    // ── Safety & Alignment ─────────────────────────────────────────────────
    {
      id: 'truthfulqa',
      name: 'TruthfulQA',
      shortName: 'TruthfulQA',
      initials: 'TQ',
      logo: 'logos/truthfulqa.png',
      stars: 937,
      forks: 119,
      description:
        'Benchmark measuring whether LLMs generate truthful answers to 817 adversarial questions spanning health, law, finance, and conspiracy — designed so models that mimic human misconceptions fail.',
      category: 'safety',
      hardware: ['cpu', 'gpu'],
      types: ['safety'],
      url: 'https://github.com/sylinrl/TruthfulQA',
      license: 'Apache 2.0',
      org: 'Oxford / ARC',
      metrics: [
        '% Truthful',
        '% Informative',
        'Truthful + Informative combined',
      ],
      tags: ['truthfulqa', 'truthfulness', 'hallucination', 'safety'],
    },
    {
      id: 'simplesafetytests',
      name: 'SimpleSafetyTests',
      shortName: 'SimpleSafety',
      initials: 'SS',
      logo: 'logos/simplesafetytests.png',
      stars: 20,
      forks: 2,
      description:
        'A minimal set of 100 test prompts across 5 harm categories that any production LLM should refuse — designed to quickly identify obvious safety failures before deploying consumer-facing models.',
      category: 'safety',
      hardware: ['cpu', 'gpu'],
      types: ['safety'],
      url: 'https://github.com/bertiev/SimpleSafetyTests',
      license: 'CC BY 4.0',
      org: 'Bertie Vidgen',
      metrics: [
        'Unsafe response rate',
        'Per-category refusal rate',
      ],
      tags: ['simplesafety', 'safety', 'refusal', 'consumer'],
    },
    {
      id: 'strongreject',
      name: 'StrongREJECT',
      shortName: 'StrongREJECT',
      initials: 'SR',
      logo: 'logos/strongreject.png',
      stars: 158,
      forks: 7,
      description:
        "Automated jailbreak evaluation framework — uses an LLM judge to score response harmfulness and refusal quality, providing consistent measurement of how well models resist adversarial prompts.",
      category: 'safety',
      hardware: ['cpu', 'gpu'],
      types: ['safety'],
      url: 'https://github.com/alexandrasouly/strongreject',
      license: 'Apache 2.0',
      org: 'Stanford / ARC',
      metrics: [
        'Refusal rate',
        'Harmfulness score (1–5)',
        'Jailbreak success rate',
      ],
      tags: ['strongreject', 'jailbreak', 'judge', 'safety'],
    },
    {
      id: 'salad-bench',
      name: 'SALAD-Bench',
      shortName: 'SALAD-Bench',
      initials: 'SB',
      logo: 'logos/salad-bench.png',
      stars: 176,
      forks: 15,
      description:
        'Safety alignment benchmark with 30,000+ question-answer pairs across 6 harm domains — evaluates base and safety-aligned models with attack-enhanced and defense-enhanced question variants for fine-grained risk profiling.',
      category: 'safety',
      hardware: ['cpu', 'gpu'],
      types: ['safety'],
      url: 'https://github.com/OpenSafetyLab/SALAD-Bench',
      license: 'MIT',
      org: 'OpenSafetyLab',
      metrics: [
        'Attack success rate',
        'Safety score',
        'Harm category breakdown',
        'Base vs. enhanced performance gap',
      ],
      tags: ['salad-bench', 'safety', 'alignment', 'harm'],
    },

    // ── Security ───────────────────────────────────────────────────────────
    {
      id: 'vloc-bench',
      name: 'VLoc Bench',
      shortName: 'VLoc Bench',
      initials: 'VL',
      description:
        'Cisco Foundation AI agentic benchmark with 500 real-world vulnerability localization tasks across six package ecosystems — models explore read-only Docker sandboxes via terminal commands to identify vulnerable files (Phase A) and confirm patched repos are clean (Phase B).',
      category: 'security',
      hardware: ['cpu', 'gpu'],
      types: ['security', 'agent'],
      url: 'https://github.com/cisco-foundation-ai/vulnerability-localization-benchmark',
      docs: 'https://cisco-foundation-ai.github.io/vulnerability-localization-benchmark/',
      license: 'Apache 2.0',
      org: 'Cisco Foundation AI',
      status: 'active',
      lastReviewed: '2026-08-12',
      metrics: [
        'File F1 (localization)',
        'True negative rate (verification)',
        'CWE coverage',
        'Per-ecosystem breakdown',
      ],
      tags: ['vloc', 'security', 'vulnerability', 'cisco', 'agentic'],
    },
    {
      id: 'garak',
      name: 'Garak',
      shortName: 'Garak',
      initials: 'GK',
      logo: 'logos/garak.png',
      stars: 8776,
      forks: 1163,
      description:
        "NVIDIA's open-source LLM vulnerability scanner — probes models for prompt injection, jailbreaks, hallucinations, data leakage, and toxicity using a modular generator/probe/detector architecture.",
      category: 'security',
      hardware: ['cpu', 'gpu'],
      types: ['security'],
      url: 'https://github.com/NVIDIA/garak',
      license: 'Apache 2.0',
      org: 'NVIDIA',
      metrics: [
        'Pass rate per probe',
        'Vulnerability detection rate',
        'Attack success rate',
      ],
      tags: ['garak', 'nvidia', 'red-team', 'jailbreak', 'probe'],
    },
    {
      id: 'harmbench',
      name: 'HarmBench',
      shortName: 'HarmBench',
      initials: 'HB',
      logo: 'logos/harmbench.png',
      stars: 1028,
      forks: 153,
      description:
        'Standardized red-teaming benchmark for LLMs — evaluates 18 attack methods against 33 target models across 400+ harmful behavior scenarios, enabling apples-to-apples comparison of safety mitigations.',
      category: 'security',
      hardware: ['cpu', 'gpu'],
      types: ['security'],
      url: 'https://github.com/centerforaisafety/HarmBench',
      license: 'MIT',
      org: 'Center for AI Safety',
      metrics: [
        'Attack success rate (ASR)',
        'Defense pass rate',
        'Jailbreak rate per category',
      ],
      tags: ['harmbench', 'red-team', 'jailbreak', 'safety'],
    },
    {
      id: 'cyberseceval',
      name: 'CyberSecEval',
      shortName: 'CyberSecEval',
      initials: 'CE',
      logo: 'logos/cyberseceval.png',
      stars: 4343,
      forks: 766,
      description:
        "Meta's Purple Llama benchmark suite for evaluating LLM cybersecurity risk — tests insecure code generation, cyberattack assistance, prompt injection susceptibility, and secure coding knowledge across multiple languages.",
      category: 'security',
      hardware: ['cpu', 'gpu'],
      types: ['security'],
      url: 'https://github.com/meta-llama/PurpleLlama',
      license: 'MIT',
      org: 'Meta / Purple Llama',
      metrics: [
        'Insecure code rate',
        'Cyberattack compliance rate',
        'Prompt injection success rate',
        'Secure coding score',
      ],
      tags: ['cyberseceval', 'meta', 'purple-llama', 'code-security'],
    },

    // ── Multimodal ─────────────────────────────────────────────────────────
    {
      id: 'mmmu',
      name: 'MMMU',
      shortName: 'MMMU',
      initials: 'MM',
      logo: 'logos/mmmu.png',
      stars: 593,
      forks: 56,
      description:
        'Massive Multidiscipline Multimodal Understanding benchmark — 11,500 college-level questions spanning art, science, engineering, medicine, and humanities, requiring complex reasoning over images, diagrams, charts, and text.',
      category: 'multimodal',
      hardware: ['cpu', 'gpu'],
      types: ['multimodal'],
      url: 'https://mmmu-benchmark.github.io',
      license: 'Apache 2.0',
      org: 'MMMU Team',
      metrics: [
        'Overall accuracy',
        'Per-discipline accuracy',
        'Reasoning accuracy',
      ],
      tags: ['mmmu', 'multimodal', 'college-level', 'vision-language'],
    },
    {
      id: 'mmbench',
      name: 'MMBench',
      shortName: 'MMBench',
      initials: 'MB',
      logo: 'logos/mmbench.png',
      stars: 310,
      forks: 19,
      description:
        'OpenCompass multimodal benchmark with 3,000+ multiple-choice questions covering 20 fine-grained capability dimensions — uses a CircularEval strategy and ChatGPT-based judging to reduce option-order bias.',
      category: 'multimodal',
      hardware: ['cpu', 'gpu'],
      types: ['multimodal'],
      url: 'https://github.com/open-compass/MMBench',
      license: 'Apache 2.0',
      org: 'Shanghai AI Lab / OpenCompass',
      metrics: [
        'Overall score',
        'Perception score',
        'Reasoning score',
        'Per-dimension accuracy',
      ],
      tags: ['mmbench', 'opencompass', 'multimodal', 'vision'],
    },
    {
      id: 'vqav2',
      name: 'VQAv2',
      shortName: 'VQAv2',
      initials: 'VQ',
      description:
        'Visual Question Answering v2 — 1.1M questions about MS-COCO images requiring understanding of objects, attributes, counts, spatial relationships, and scene context. A foundational benchmark for vision-language models.',
      category: 'multimodal',
      hardware: ['cpu', 'gpu'],
      types: ['multimodal'],
      url: 'https://visualqa.org',
      license: 'CC BY 4.0',
      org: 'Virginia Tech / Georgia Tech',
      metrics: [
        'Overall accuracy',
        'Open-ended accuracy',
        'Yes/No accuracy',
        'Number accuracy',
      ],
      tags: ['vqav2', 'vqa', 'visual-qa', 'vision-language'],
    },
    {
      id: 'seed-bench',
      name: 'SEED-Bench',
      shortName: 'SEED-Bench',
      initials: 'SD',
      logo: 'logos/seed-bench.png',
      stars: 366,
      forks: 13,
      description:
        "Tencent's multimodal benchmark with 19,000 multiple-choice questions across 12 evaluation dimensions — covers spatial understanding, visual reasoning, and video temporal comprehension, supporting both image and video models.",
      category: 'multimodal',
      hardware: ['cpu', 'gpu'],
      types: ['multimodal'],
      url: 'https://github.com/AILab-CVC/SEED-Bench',
      license: 'Apache 2.0',
      org: 'Tencent ARC',
      metrics: [
        'Overall accuracy',
        'Image understanding accuracy',
        'Video understanding accuracy',
        'Per-dimension score',
      ],
      tags: ['seed-bench', 'tencent', 'multimodal', 'video'],
    },

    // ── Production & Observability ─────────────────────────────────────────
    {
      id: 'langsmith',
      name: 'LangSmith',
      shortName: 'LangSmith',
      initials: 'LS',
      logo: 'logos/langsmith.png',
      stars: 1014,
      forks: 274,
      description:
        'LangChain platform for tracing, evaluating, and monitoring LLM applications in development and production — supports dataset-based evals, online feedback, and regression testing.',
      category: 'quality',
      hardware: ['cpu'],
      types: ['quality', 'rag', 'agent'],
      url: 'https://github.com/langchain-ai/langsmith-sdk',
      docs: 'https://docs.smith.langchain.com',
      license: 'MIT',
      org: 'LangChain',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['production-monitoring', 'pre-production', 'ci-friendly'],
      related: ['ragas', 'deepeval', 'arize-phoenix'],
      metrics: [
        'Evaluation run accuracy',
        'Latency traces',
        'Cost per trace',
        'Human feedback scores',
      ],
      tags: ['langchain', 'observability', 'tracing', 'production'],
    },
    {
      id: 'arize-phoenix',
      name: 'Arize Phoenix',
      shortName: 'Phoenix',
      initials: 'PX',
      logo: 'logos/arize-phoenix.png',
      stars: 11014,
      forks: 1054,
      description:
        'Open-source LLM observability and evaluation platform — traces RAG pipelines, runs eval experiments, and surfaces retrieval quality issues with embedding visualization.',
      category: 'rag',
      hardware: ['cpu'],
      types: ['rag', 'quality', 'embedding'],
      url: 'https://github.com/Arize-ai/phoenix',
      docs: 'https://docs.arize.com/phoenix',
      license: 'Apache 2.0',
      org: 'Arize AI',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['production-monitoring', 'pre-production', 'research'],
      related: ['ragas', 'trulens', 'langsmith'],
      metrics: [
        'Retrieval precision / recall',
        'Embedding drift',
        'Latency percentiles',
        'Eval experiment scores',
      ],
      tags: ['arize', 'observability', 'rag', 'tracing'],
    },
    {
      id: 'tensorrt-llm',
      name: 'TensorRT-LLM Benchmarks',
      shortName: 'TRT-LLM',
      initials: 'TR',
      logo: 'logos/tensorrt-llm.png',
      stars: 14369,
      forks: 2658,
      description:
        "NVIDIA's TensorRT-LLM benchmarking suite for measuring LLM inference throughput and latency on NVIDIA GPUs with optimized kernels, quantization, and multi-GPU serving.",
      category: 'inference',
      hardware: ['gpu'],
      types: ['online', 'offline'],
      url: 'https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks',
      docs: 'https://nvidia.github.io/TensorRT-LLM',
      license: 'Apache 2.0',
      org: 'NVIDIA',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['pre-production', 'ci-friendly', 'cost-analysis'],
      related: ['genai-perf', 'vllm-throughput', 'perf-analyzer'],
      metrics: [
        'Token throughput (tok/s)',
        'TTFT',
        'Memory usage',
        'Cost per million tokens',
      ],
      tags: ['nvidia', 'tensorrt', 'gpu', 'inference'],
    },
    {
      id: 'tgi-bench',
      name: 'Text Generation Inference',
      shortName: 'TGI',
      initials: 'TG',
      logo: 'logos/tgi-bench.png',
      stars: 10886,
      forks: 1277,
      description:
        "Hugging Face's production LLM serving stack with built-in benchmarking for throughput and latency — supports continuous batching, quantization, and OpenAI-compatible APIs. Repository archived in March 2026 after entering maintenance mode; Hugging Face recommends vLLM or SGLang for new deployments.",
      category: 'inference',
      hardware: ['gpu'],
      types: ['online'],
      url: 'https://github.com/huggingface/text-generation-inference',
      docs: 'https://huggingface.co/docs/text-generation-inference',
      huggingface: 'https://huggingface.co/docs/text-generation-inference',
      license: 'Apache 2.0',
      org: 'Hugging Face',
      status: 'archived',
      lastReviewed: '2026-08-12',
      useCases: ['pre-production', 'api-benchmarking'],
      related: ['vllm-serve', 'genai-perf', 'genai-bench'],
      metrics: [
        'Request throughput (req/s)',
        'TTFT',
        'Token throughput (tok/s)',
        'Batch size efficiency',
      ],
      tags: ['huggingface', 'tgi', 'serving', 'gpu', 'archived'],
    },
    {
      id: 'wandb-weave',
      name: 'Weights & Biases Weave',
      shortName: 'W&B Weave',
      initials: 'WB',
      logo: 'logos/wandb-weave.png',
      stars: 1115,
      forks: 161,
      description:
        'W&B toolkit for LLM tracing, evaluation, and experiment tracking — run scorers on datasets, compare model versions, and monitor production LLM apps.',
      category: 'quality',
      hardware: ['cpu'],
      types: ['quality', 'rag', 'agent'],
      url: 'https://github.com/wandb/weave',
      docs: 'https://wandb.github.io/weave',
      license: 'Apache 2.0',
      org: 'Weights & Biases',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['production-monitoring', 'research', 'ci-friendly'],
      related: ['langsmith', 'arize-phoenix', 'helm'],
      metrics: [
        'Scorer accuracy',
        'Latency traces',
        'Experiment comparisons',
        'Regression detection',
      ],
      tags: ['wandb', 'weave', 'observability', 'evaluation'],
    },

    // ── Benchmark Orchestration ────────────────────────────────────────────
    {
      id: 'vllm-cpu-perf-eval',
      name: 'cpueval (vLLM CPU Perf Eval)',
      shortName: 'cpueval',
      initials: 'CE',
      stars: 8,
      forks: 6,
      description:
        'Red Hat ET benchmark orchestration framework — cpueval CLI drives Ansible playbooks across DUT and load-generator hosts to run reproducible inference suites (concurrent load, offline batch, embedding, audio) with MLflow tracking and Streamlit dashboards.',
      category: 'benchmark-orchestration',
      hardware: ['cpu'],
      types: ['online', 'offline', 'embedding', 'audio'],
      url: 'https://github.com/redhat-et/vllm-cpu-perf-eval',
      docs: 'https://redhat-et.github.io/vllm-cpu-perf-eval/',
      license: 'Apache 2.0',
      org: 'Red Hat Emerging Technologies',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['pre-production', 'ci-friendly', 'api-benchmarking', 'research'],
      related: ['vllm-serve', 'guidellm', 'mteb', 'inference-perf', 'llm-d-bench', 'llm-d-benchmark'],
      metrics: [
        'TTFT – Time To First Token',
        'Token throughput (tok/s)',
        'Request throughput (req/s)',
        'Embedding quality (MTEB)',
        'Inter-token latency',
      ],
      tags: ['vllm', 'cpu', 'red-hat', 'ansible', 'automation', 'methodology'],
    },
    {
      id: 'llm-d-benchmark',
      name: 'llm-d Benchmark',
      shortName: 'llm-d bench',
      initials: 'LD',
      stars: 64,
      forks: 125,
      description:
        'Kubernetes benchmark orchestration for llm-d inference stacks — plan, standup, smoketest, run, teardown, and experiment commands provision model-serving infrastructure, deploy harness pods (inference-perf, GuideLLM, vLLM bench), and generate standardized analysis reports.',
      category: 'benchmark-orchestration',
      hardware: ['cpu', 'gpu'],
      types: ['online', 'offline'],
      url: 'https://github.com/llm-d/llm-d-benchmark',
      license: 'Apache 2.0',
      org: 'llm-d',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['pre-production', 'ci-friendly', 'api-benchmarking', 'research'],
      related: ['inference-perf', 'guidellm', 'vllm-serve', 'genai-bench', 'llm-d-bench'],
      metrics: [
        'TTFT – Time To First Token',
        'Token throughput (tok/s)',
        'Request throughput (req/s)',
        'Deployment health checks',
        'DoE experiment comparisons',
      ],
      tags: ['kubernetes', 'llm-d', 'orchestration', 'inference-perf', 'experiment'],
    },
    {
      id: 'llm-d-bench',
      name: 'llm-d-bench',
      shortName: 'llm-d-bench',
      initials: 'LB',
      stars: 0,
      forks: 3,
      description:
        'OpenShift PSAP Tekton pipelines for end-to-end LLM inference benchmarking — deploys llm-d, RHOAI, or RHAIIS stacks, runs GuideLLM or MLPerf harnesses, tracks experiments in MLflow, and tears down resources automatically.',
      category: 'benchmark-orchestration',
      hardware: ['cpu', 'gpu'],
      types: ['online', 'offline'],
      url: 'https://github.com/openshift-psap/llm-d-bench',
      license: 'Apache 2.0',
      org: 'OpenShift PSAP / Red Hat',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['pre-production', 'ci-friendly', 'api-benchmarking', 'research'],
      related: ['guidellm', 'mlperf', 'inference-perf', 'vllm-cpu-perf-eval', 'llm-d-benchmark'],
      metrics: [
        'TTFT – Time To First Token',
        'Token throughput (tok/s)',
        'Request throughput (req/s)',
        'MLPerf scenario scores',
        'MLflow experiment metrics',
      ],
      tags: ['openshift', 'tekton', 'red-hat', 'mlflow', 'mlperf', 'guidellm'],
    },
    {
      id: 'mlcommons-cm',
      name: 'MLCommons Collective Mind',
      shortName: 'MLCommons CM',
      initials: 'CM',
      stars: 650,
      forks: 123,
      description:
        'MLCommons automation framework (CM) for reproducible MLPerf inference runs — chains modular scripts to prepare environments, build containers, and execute benchmark pipelines across diverse models, datasets, software stacks, and hardware targets.',
      category: 'benchmark-orchestration',
      hardware: ['cpu', 'gpu'],
      types: ['online', 'offline'],
      url: 'https://docs.mlcommons.org/cm4mlops/scripts/Modular-MLPerf-inference-benchmark-pipeline/app-mlperf-inference/',
      docs: 'https://github.com/mlcommons/ck',
      license: 'Apache 2.0',
      org: 'MLCommons',
      status: 'active',
      lastReviewed: '2026-08-12',
      useCases: ['pre-production', 'ci-friendly', 'research'],
      related: ['mlperf'],
      metrics: [
        'MLPerf latency (p50 / p90 / p99)',
        'Throughput (samples/s)',
        'Target QPS compliance',
        'Accuracy vs performance modes',
      ],
      tags: ['mlcommons', 'mlperf', 'automation', 'reproducibility', 'containers'],
    },
  ],
};

/* ── Enrichment: defaults, use cases, and related tools ───────────────── */
const RELATED_MAP = {
  'vllm-serve':       ['guidellm', 'llmperf', 'genai-perf', 'tgi-bench', 'vllm-cpu-perf-eval', 'llm-d-benchmark'],
  'vllm-throughput':  ['tensorrt-llm', 'perf-analyzer'],
  'guidellm':         ['vllm-serve', 'llmperf', 'genai-perf', 'vllm-cpu-perf-eval', 'llm-d-benchmark', 'llm-d-bench'],
  'llmperf':          ['vllm-serve', 'guidellm', 'tgi-bench'],
  'genai-perf':       ['vllm-serve', 'perf-analyzer', 'tensorrt-llm', 'llm-d-benchmark'],
  'inference-perf':   ['llm-d-benchmark', 'llm-d-bench', 'vllm-serve', 'guidellm'],
  'mlperf':           ['mlcommons-cm', 'llm-d-bench'],
  'vllm-cpu-perf-eval': ['vllm-serve', 'guidellm', 'mteb', 'inference-perf', 'llm-d-bench', 'llm-d-benchmark'],
  'llm-d-benchmark':  ['inference-perf', 'guidellm', 'vllm-serve', 'genai-bench', 'llm-d-bench'],
  'llm-d-bench':      ['guidellm', 'mlperf', 'inference-perf', 'vllm-cpu-perf-eval', 'llm-d-benchmark'],
  'mlcommons-cm':     ['mlperf'],
  'helm':             ['lm-eval', 'openai-evals'],
  'lm-eval':          ['helm', 'openai-evals'],
  'humaneval':        ['bigcodebench', 'livecodebench'],
  'livecodebench':    ['humaneval', 'swe-bench'],
  'swe-bench':        ['livecodebench', 'humaneval'],
  'ragas':            ['deepeval', 'trulens', 'arize-phoenix'],
  'deepeval':         ['ragas', 'trulens'],
  'trulens':          ['ragas', 'deepeval', 'arize-phoenix'],
  'mteb':             ['beir', 'air-bench-retrieval'],
  'beir':             ['mteb', 'air-bench-retrieval'],
  'truthfulqa':       ['simplesafetytests', 'strongreject'],
};

const TOOL_META = {
  'vllm-serve': {
    hosting: 'self-hosted', outputFormats: ['json', 'prometheus'], modelScope: 'agnostic',
    adoption: 'both', datasets: ['ShareGPT', 'custom prompts'],
  },
  'vllm-throughput': {
    hosting: 'library', outputFormats: ['json', 'csv'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['synthetic workloads'],
  },
  'vllm-cpu-perf-eval': {
    hosting: 'self-hosted', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'research', foundation: 'Red Hat ET',
    datasets: ['concurrent-load', 'offline-batch', 'MTEB', 'audio workloads'],
  },
  'llm-d-benchmark': {
    hosting: 'self-hosted', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['inference-perf profiles', 'GuideLLM sweeps', 'vLLM bench'],
  },
  'llm-d-bench': {
    hosting: 'self-hosted', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', foundation: 'Red Hat',
    datasets: ['GuideLLM workloads', 'MLPerf scenarios'],
  },
  'mlcommons-cm': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'both', foundation: 'MLCommons', datasets: ['MLPerf Inference workloads'],
  },
  'mlperf': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'both', foundation: 'MLCommons', datasets: ['MLPerf Inference', 'MLPerf Training'],
  },
  'guidellm': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'openai-compatible',
    adoption: 'both', datasets: ['custom prompts'],
  },
  'inferx': {
    hosting: 'self-hosted', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'production', datasets: ['custom workloads'],
  },
  'genai-perf': {
    hosting: 'library', outputFormats: ['json', 'csv'], modelScope: 'openai-compatible',
    adoption: 'both', datasets: ['synthetic prompts'],
  },
  'llmperf': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'openai-compatible',
    adoption: 'both', datasets: ['custom prompts'],
  },
  'perf-analyzer': {
    hosting: 'library', outputFormats: ['json', 'prometheus'], modelScope: 'agnostic',
    adoption: 'both', foundation: 'NVIDIA', datasets: ['synthetic workloads'],
  },
  'helm': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['MMLU', 'TruthfulQA', 'BBQ', 'RAFT'],
  },
  'lm-eval': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'huggingface',
    adoption: 'research', datasets: ['MMLU', 'HumanEval', 'GSM8K', 'HellaSwag'],
  },
  'openai-evals': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'openai-compatible',
    adoption: 'research', datasets: ['custom eval sets'],
  },
  'humaneval': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['HumanEval'],
  },
  'swe-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['SWE-bench'],
  },
  'bigcodebench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['BigCodeBench'],
  },
  'livecodebench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['LiveCodeBench'],
  },
  'bfcl': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['BFCL'],
  },
  'agentbench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['AgentBench'],
  },
  'tau-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['τ-bench'],
  },
  'webarena': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['WebArena'],
  },
  'ragas': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'both', datasets: ['custom RAG datasets'],
  },
  'deepeval': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'openai-compatible',
    adoption: 'both', datasets: ['custom test cases'],
  },
  'trulens': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'both', datasets: ['custom feedback sets'],
  },
  'promptfoo': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'openai-compatible',
    adoption: 'both', datasets: ['custom prompt sets'],
  },
  'mteb': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'huggingface',
    adoption: 'research', datasets: ['MTEB'],
  },
  'beir': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['BEIR'],
  },
  'air-bench-retrieval': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['AIR-Bench'],
  },
  'whisper-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'huggingface',
    adoption: 'research', datasets: ['LibriSpeech', 'Common Voice'],
  },
  'esb': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'huggingface',
    adoption: 'research', datasets: ['ESB'],
  },
  'voice-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['VoiceBench'],
  },
  'superb': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'huggingface',
    adoption: 'research', datasets: ['SUPERB'],
  },
  'truthfulqa': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['TruthfulQA'],
  },
  'simplesafetytests': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['SimpleSafetyTests'],
  },
  'strongreject': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['StrongREJECT'],
  },
  'salad-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['Salad-Bench'],
  },
  'vloc-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'openai-compatible',
    adoption: 'research', foundation: 'Cisco Foundation AI', datasets: ['VLoc Bench'],
  },
  'garak': {
    hosting: 'library', outputFormats: ['json', 'html'], modelScope: 'openai-compatible',
    adoption: 'both', datasets: ['Garak probes'],
  },
  'harmbench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['HarmBench'],
  },
  'cyberseceval': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', foundation: 'Meta', datasets: ['CyberSecEval'],
  },
  'mmmu': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['MMMU'],
  },
  'mmbench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['MMBench'],
  },
  'vqav2': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['VQA v2'],
  },
  'seed-bench': {
    hosting: 'library', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'research', datasets: ['SEED-Bench'],
  },
  'langsmith': {
    hosting: 'both', outputFormats: ['json'], modelScope: 'agnostic',
    adoption: 'production', foundation: 'LangChain', datasets: ['custom eval datasets'],
  },
  'arize-phoenix': {
    hosting: 'both', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'production', datasets: ['custom eval datasets'],
  },
  'tensorrt-llm': {
    hosting: 'library', outputFormats: ['json', 'csv'], modelScope: 'provider-specific',
    adoption: 'both', foundation: 'NVIDIA', datasets: ['synthetic workloads'],
  },
  'tgi-bench': {
    hosting: 'self-hosted', outputFormats: ['json', 'prometheus'], modelScope: 'huggingface',
    adoption: 'both', foundation: 'Hugging Face', datasets: ['ShareGPT', 'custom prompts'],
  },
  'wandb-weave': {
    hosting: 'both', outputFormats: ['json', 'html'], modelScope: 'agnostic',
    adoption: 'both', foundation: 'Weights & Biases', datasets: ['custom scorer datasets'],
  },
};

const inferUseCases = (tool) => {
  const cases = [];
  if (tool.types.includes('online')) cases.push('pre-production', 'api-benchmarking');
  if (tool.types.includes('offline')) cases.push('ci-friendly');
  if (['quality', 'code', 'agent', 'rag', 'embedding', 'multimodal', 'safety', 'security'].some((t) => tool.types.includes(t))) {
    cases.push('leaderboard', 'research');
  }
  if (tool.tags?.some((t) => ['cost', 'serving', 'concurrency'].includes(t))) cases.push('cost-analysis');
  return [...new Set(cases)];
};

LANDSCAPE.tools.forEach((t) => {
  t.status = t.status || 'active';
  t.lastReviewed = t.lastReviewed || '2026-08-12';
  t.useCases = t.useCases || inferUseCases(t);
  t.related = t.related || RELATED_MAP[t.id] || [];
  const meta = TOOL_META[t.id];
  if (meta) Object.assign(t, meta);
});
